version: "3"
services:
  besu:
    image: proycertificados/colprofede-besu
    container_name: besu
    environment:
      - BESU_P2P_HOST=${BESU_P2P_HOST}
    ports:
      - 30303:30303/udp
      - 30303:30303/tcp
      - 8545:8545
    volumes:
      - ./genesis.json:/config/besu/genesis.json
      - ./keys/besu/key:/opt/besu/data/key
      - ./besu-database:/opt/besu/data/database
    command: ["--config-file=/config/besu/config.toml"]
