version: '3.8'
services:
  colprofede-api:
    image: proycertificados/colprofede-client-api
    container_name: colprofede-api-container
    ports:
       - 3000:3000 # API Rest Services - expose if needed/wanted
    environment:
       - IPFS_PORT=5001
       - IPFS_HOST=IPFS_HOST # IMPORTANT - Change this IP
       - IPFS_PROTOCOL=http
       - BESU_PORT=8545
       - BESU_HOST=IPFS_HOST # IMPORTANT - Change this IP
       - BESU_PROTOCOL=http
  ipfs:
    image: proycertificados/colprofede-ipfs
    container_name: ipfs
    ports:
       - '4001:4001' # IPFS swarm - expose if needed/wanted
       - '5001:5001' # IPFS api - expose if needed/wanted
       - '8080:8080' # IPFS gateway - expose if needed/wanted
  besu:
    image: proycertificados/colprofede-besu
    container_name: besu
    environment:
      - BESU_P2P_HOST=${BESU_P2P_HOST}
    ports:
      - 30303:30303/udp
      - 30303:30303/tcp
      - 8545:8545
    volumes:
      - ./genesis.json:/config/besu/genesis.json
      - ./keys/besu/key:/opt/besu/data/key
      - ./besu-database:/opt/besu/data/database
    command: ["--config-file=/config/besu/config.toml"]